### ISSUE TITLE
pre-generated assets

### ISSUE THREAD

**Issue by NikolausDemmel** [tkonolige/city2ba#3]
Hi, I just came across your tool. This looks very interesting, thanks for sharing!

I'm wondering if you have a collection pre-generated BAL problems from this tool and/or  .obj assets for testing BA problems that you'd be willing to share?

**Comment by tkonolige** [comment]
I have a selection of BAL problems that I've generated, but it would probably be easiest for you to generate them yourself from the model I used. The model is a 3D model of Zwolle from https://3d.bk.tudelft.nl/opendata/3dfier/ (this link now 404s, maybe the data has moved to https://docs.3dbag.nl/en/?). Here is a copy of it which I've modified to have some camera tracks: https://drive.google.com/file/d/1943F7I7dEXQqZSwXq0kK8zTnshDOJBOF/view?usp=sharing. There are a couple of tracks to choose from: `Loop_BezierCurve` a single loop, `Long_path_BezierCurve.001` a long path that does not intersect itself or loop, `Small_Loop_BezierCurve.002` a small loop around a single building, `complicated_inner_city_BezierCurve.004` a complicated path through a small portion of the city, and `whole_city_BezierCurve.010` a complicated path through the whole city. The largest problem I've worked with is generated via `city2ba generate ../models/zwolle.obj 100K_whole_city.bbal --cameras 100000 --points 1000000 --max-dist 40 --path whole_city_BezierCurve.010`. If you want the specific problems I've worked with, I could probably upload them somewhere.

If you want to find more models, I would recommend looking at https://3d.bk.tudelft.nl/opendata/opencities/. To add camera tracks to models, I've been using blender. You can draw a line and then project it onto the terrain using the shrinkwrap modifier.

**Comment by NikolausDemmel** [comment]
Thanks for sharing these details and assets! This is really helpful. I'll give it a try.
